---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: jellyfin-cm
    files:
      - config/database.xml
      - config/encoding.xml
      - config/network.xml
      - config/system.xml
