---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    namespace: kube-system
    version: 1.43.3
    releaseName: coredns
    valuesFile: values.yaml
