apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
metricsProviders:
  - source: KubernetesMetrics
profiles:
  - name: default
    pluginConfig:
      - name: RemoveDuplicates
      - name: RemovePodsHavingTooManyRestarts
        args:
          podRestartThreshold: 100
          includingInitContainers: true
      - name: RemovePodsViolatingNodeAffinity
        args:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
      - name: RemovePodsViolatingNodeTaints
      - name: RemovePodsViolatingInterPodAntiAffinity
      - name: RemovePodsViolatingTopologySpreadConstraint
      - name: LowNodeUtilization
        args:
          thresholds:
            memory: 60
            cpu: 70
          targetThresholds:
            memory: 80
            cpu: 90
          metricsUtilization:
            source: KubernetesMetrics
    plugins:
      balance:
        enabled:
          - RemoveDuplicates
          - RemovePodsViolatingTopologySpreadConstraint
          - LowNodeUtilization
      deschedule:
        enabled:
          - RemovePodsHavingTooManyRestarts
          - RemovePodsViolatingNodeTaints
          - RemovePodsViolatingNodeAffinity
          - RemovePodsViolatingInterPodAntiAffinity
