---
k8sServiceHost: 192.168.0.210
k8sServicePort: 6443

l2announcements:
  enabled: true

l2NeighDiscovery:
  enabled: true

k8sClientRateLimit:
  qps: 50
  burst: 200

kubeProxyReplacement: true
l7Proxy: true

externalIPs:
  enabled: true

hubble:
  ui:
    enabled: true
  relay:
    enabled: true

operator:
  rollOutPods: true

rollOutCiliumPods: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.0.50
  secretsNamespace:
    create: true
    sync: true

rbac:
  create: true

tls:
  secretSync:
    enabled: true
  secretsNamespace:
    create: true

gatewayApi:
  enabled: true
