---
k8sServiceHost: 192.168.0.210
k8sServicePort: 6443

l2announcments:
  enabled: true

l2NeighDiscovery:
  enabled: true

k8sClientRateLimit:
  qps: 50
  burst: 200

kubeProxyReplacement: true

externalIPs:
  enabled: true

hubble:
  ui:
    enabled: true
  relay:
    enabled: true

operator:
  rollOutPods: true

rollOutCiliumPods: true
