---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: grafana-db-dump
  labels:
    name: grafana
spec:
  backupCommand: sh -c 'sqlite3 /data/grafana.db .dump'
  pod:
    spec:
      containers:
        - name: grafana-sqlite-dump
          image: alpine/sqlite:3.51.2
          command:
            - 'sleep'
            - 'infinity'
          volumeMounts:
            - name: grafana-pvc
              mountPath: "/data"
      volumes:
        - name: grafana-pvc
          persistentVolumeClaim:
            claimName: grafana-pvc
