---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  annotations:
    k8up.io/backup: true
  labels:
    name: grafana
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: grafana-pvc
    namespace: observability
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/grafana
    mountOptions:
      - noatime
      - vers=3
      - soft
      - timeo=600
      - retrans=5
      - rsize=8192
      - wsize=8192
      - lookupcache=none
      - tcp
    server: 192.168.0.222
