---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
spec:
  encryptedData:
    admin-password: AgBH7PzGHT2v8R8eUOoRrvKAHVdWOottsikyr8o4eFZxKiIYUmUq5iD+A/N4cP4kILEFIzV2nbss6jRKC1vdDZKPdxlNYtdhOLJJdiNBk6anXtMCL9Vb4gl2Ukxju4zMcEtx4DHZ6+eDaxM+oiKu8/n/VZpRQociHeGUxdJxJSD4CcJiY/tUQuLS7QKoU4Cbuy399yF4j5DCYDPtsxI0Tsatfs18r5Nx4GPeuxgnC8jaFEwlP9orYC35fnoVCr7OSePPreJG94DJ62zVCDWMeLv0paanLT6DTcTWsz2l9BxNUnziJ6MRp5Q/ROO6J9cbcNI/+AsCaUM7xfRnwfa1SVieANV72fWui7+MU2uZY5HA9SM3QXiQwuorQcI3hht0M/PDiFsqTSXN3/7BV+/+4Ljb0O+UUwJSSs3croc1B55EOVlJ1S+hsPK+oHc2iSV0iNqYrJBencG2JqPoraCtWlxkrNAJxeo3200TK71U/WWoCSlpmghnppMAoazu6neUDvz3YUFJy3NMh/P02rjFI3Z/Duo8U7P2KaPhqrSQt52ZjL3p8SXSb7lSiOA9KXcvubHHZEhW05PaLPY4Zz7/dWdwsucFNgKhGHpAZYGD4WEJNhZQMs6eR537dg9Qu28zkzREJOl5lZ3q642y3Q3rAnfNHnBCNsp8oLx3K+NGDnrva272uTJuzKCX+HmPaMQIpFUflG0vKMD3+aa/
    admin-user: AgB62x6s9uOWyGHcG3tfh7NDYfxbzGGRqh2dFqUUnYYpiNGArSIGO92XooACBeZ/Ipgeh3Opxl50kAQ9fTOkLkv6p67r22DQGAfVsqsGFZWwWvSBzf9hdmVN7r5EdK1eN1mbN1RtmRlSeTCUY8UBSbC8Nb3thuy5JwK9xyGsBNfDkbJelJoJQTrhO25cqCUl2G9aYEfowfV8kkSXybDEVIuKVmcdVoICCfHADKFEUL8Gv44wMXinA/xje5Uq9zFn7jBmayseogCSgXG3yj3H2WcJy9MDJKu/xkqwOq9aA2gmIE3AhlggwyvHuOkxWqcVZGE5S7i444xTjwM12I0KDPrl0yg1ErJ33TB7nBBlIKjq6eUXO5LTna1Q9Lr8JyflZEEuHg+e13MkqkQ3b5ScAfmlExOPwbAh6m2XCx5AA7HphbktSndySnBJH6dKqZM9NvtZjFZUCdYYq3Oh5JeY6+1bFj36sNLV922r6jRSszb9Oqqm3ifoMGNX39l1wPv73ymA7zaXsoRpTGXcLwUsQaOcE0hhFcSYxYmIXKUcnF/F5Ehho3Dmv21/cISZ/x6XP6tb0bg/QQfmuGG3d1RgkMA9wICPWaIhOp9VyXuOF+5JgLrbrC6StKRlhx36+a7s8fjQKYzlmhX2OAJyrmFGWTUlgxHsIE65sEdMhPIwZOQAKk4+xQXe0/SUw0nSxuZOsBR57tbBYw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
    type: Opaque
