---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
spec:
  encryptedData:
    admin-password: AgCSPLIwAt+KiiA6HA7yrvCjv9eXNBxpj1zTF7dtIaR+fHLGRqxj04eOHNUWTTojOMSVh+dIEEmgEUmFLUQX32na+kAoc/LeexziNtVVXd1BEzjOEGshEx3v5GDOktnEkWo+ATD6Uuw2xp/plP3bHgL+HIzg6Njpu2U2vechsxrWIQe0HomFF5w3EMJar7acucPZU6tswNyAkKC8OSXeltkWnacGUbHp3Y+r+4JBLr2Uay/H6UTCSYx1Wbib1vCIBOdKW5JlJA26lWkSekIHuodge38yevH1UkQNHN7Mg8DCQjlbRFTsQGno04F6ZMMPuEqjRXadeybTP0vvr76YWSc8ccEhqbYE3PGwVws2n7A+/KeUD6dTK7pIOvBsb6T3nVv4C6Clzz8sMsmAdVXOleE2fZ1M1OyH8Sa/AWKDO43wIK9ut4ERjcrBIeEOxFo7DNoCtsMVXJ0nDh8m6ByOasf+a9fkG3qn7TVWIf+LtPWpwwVALPDlUMtboOPAG5rrU4hPZtUyvipQlT24KiJTU3R17EW4tgWb0TIKiAlSRIRyAzM8kOZ+l7Luog6d4LTdbeOzBU9kv4lopwo1MxK3VyoT7JwFp2NJwx3Z9/39TzTtEBfevvIQGddj8S78nwJdtqlO+wFFs+/R0Hz5ZCBXWxskF3a/qNjL8jlF57kELp/odjhhfy8M7XphB56g2cQAO/muPv/OFBOnIvx8
    admin-user: AgAlEz1/kXTZcwKnB8qbseeLZWzTfHN9eyzHPU7NoWkhfnX9uefFeQW21WI82CHpGmvTcdvpYNiXfJixfg53AtfOAG8xP05130lfaBwOOSaUxFJrGaHjY1seYPQKEcV8DW3oFT1zKg8FZbrW/Go782i8lYHfK/pKPH6U7p0Gf/p2qwzSRtZblQ1uoCrociZ4wyUF1L7XJGD/7XPnYfgxVQPcVDqB2N6ORXRhdChNmMMWrMaFMIDDzh8I4mpgw9rubAd9Nu1QZ9Qav5DuYz9rtOyWuyNS5TNflsmtZU5ym3eBX2a1EnYsghgzF6mijjhygHPtiDQ3eay14QtqvxMZ4dE4fz/5L648PISxsuzmEotOPTCs3bIzu09wfxX3bM0KmE8soCxftwiyT4Ixepzi9516gIRvedks3OLrKSKtncuFoMNpaE1zFCTgWqV2Y7Eu5VsDK0rz9jvVe5ThpB+G+Pw8ZVS/jW2Z/b/GmHhsxBMh9SeS6YaMnCxQaiI5vgnm0jNHwD29OJJsqTDA/0NWs43SZfC45uuCDoP2FNqIH/eCY9BM233VSMNpq90NzaP3NFZYRSPGnGwFR2icgLTd/uQnHmR/9lRSwABJQkzzQS3naPRqPd1G4aAyJXLfB/spDe36EMMR47UiP07Z6oHpVXCH610i5Cy6euYibjvjpQyCWFfjWLpnt25MQSDpfE4erwzO+ev3sg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: auth-generic-oauth-secret
spec:
  encryptedData:
    client_id: AgBevWYKv0kgEOsNrG0S3rHVhbkDjMsbwGIycT7iQ3nIb9Lv8NNfW08dZUVt2XcgN8jBiM46Xh89c4BuRh8Ahg6Kgpp8jjG3zHbe0gtYU6BrXrPHz9IvOdRnguyDazEbmE68nnDHSzUdkK2VwsH0VFDV/R2z1OH7cUa+0sw/PPsXvPucbk2icW/lOTEZaj+DyK6n+V0RxTkkdQ266BqXuFByuaqiL9s6yt1W4s8Cy4dLiL5LkBy2Dq7HESHr/BuFzHzylqvCTAb8kKVgk4SeYEO8VFzTJjV9JA+6DSqcVos7X1rDXlnEQE8rMVtphwELd2S4QFbsHZBBf9Mu6mi5EzG/vBI0LBRlucip7rpWsLluXRuVZkYgRvIMeXxsN7OPPCg4An89SiIKEqfyrUXVR0oZ14iNUOAJOW2ZEP5RdqqQSXTTpdlBZOUGDksAOhEvnPhEGVit+MOxUTS5JVS6i3AxJpQJRvOW3mCY0PtiFi0mDfTNJ/2E7Z5iCJo6pzcaRoE3bGEW1puO96T2wTbfXcXRc2t1/gQYp62yL4yG9GWS5e2eccOb/zsV3reUcP1TUoiGEwZaZI9aKKjdP3ErJ45tfMn5SecDBJpAGbzRLwYPe3cjsRLSgJ7yOh7OMrmlYpTtEMgfH4hu6pobsTe9OQQ2juhEG35xrkz6d6jtF/zY0N8TxR91SxwDEpiJrgBUsYND+lkJHSYMzIt0ooRVDBeyJ553cwr0MxAZ5mKxC8Hn9OhHAN8pynLl
    client_secret: AgDGjQKnHopUm1YdRZ24UkFcfELgVr21i69hywK+JJQrSMKtGqqVbLehI4/rs4C9wFdMrXHPnsen19ARtqWVoYN9M4Mw3zy7tW/u8IVN/37zZdAILwiIi5tC87RKzTipgZJjYxW+LfsVT+nUrAEEeOjn69eN1M5DXez1NvsAIzsb2KqmVQDwQTCmcOm8qi3jbJ1poN/ra08zNZAj+Kc3tjaRgEVjSDvl/Tw1v44NczUnmuQwgSBJOD++RejBIfLwHZsCjhYBmX6sJY3anfQHQ8E4sWxELQMIU0WzlPtuxy5mVzn1CBnaTGuwCZ8QuUEh63h+B5+dBBN4kfDMumq7vQZOur1tIGQME8KjoZxbdN3FZwTHXSGlGuxy+/MeELcGpeA76ty4xrFI477Kug2DYD9mQrK6JCPP7xPbry2uRPW+resD9o6ME6Vp2VlSJymJfefOJ+MA9a4QbtcrTsPdDd51tdqrpIH9hdjLsKGWtJaUy7kRhtOGKDChkQkl/8Cd4+FQtn7jcsDMANlsMJ5zslbe+xHbrajvFvXZwnvpTOGimqV7HOc23UeJAPqkD1jJgN+jIrlVZ6QQHWyv4NWLB6TSPR8EXj99hdKQDzQwuYBAs+MeQwo6l53HRIM34JxXH2fma/6R4GHJNjlgICd5OiIN1QLntG7hcFUH0q+yr3m0O9mKQ7OSOoHrfAk33rlkxhYlik/c2GAdkIQ3O7F66xmP3Y5AgzqJDbLVYfoLx1Kcp6yzBelf1cUWm0oCZP1hMzkBvJ4RaRi2bAFNsawkZFn2zfb1BBZNvFRKtZc1z9OORbN/D+g+C/b2j4NfhCK6wDNcCXsL1bOJUfnxr2tFDvGJGIUvqPLh2IZnkk3yMbaaSg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: auth-generic-oauth-secret
    type: Opaque
