---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
spec:
  encryptedData:
    admin-password: AgBWtmjXbzY8VZu/yJCapgW1Zn8rHDawVlQEwkYeia8qVwq2gWy3hyxXBcXeRITm2QPwLO0h3MiIQde1xxDHgEzAv2LKXftaY3VOCxkw53QZvGjIrFQyClNNUUZW53tLr0P2BzXASB805kUq343hg2gn27vdBkehCp8pcCKsbGdVwMJK87FQpGsq/dsprWyHErIhY9DOnGUr9pCURNTGFgg8z4Mj43AS1RZfJZRg/d2K9zxyZk2c8hCkBPoUA3Bl9LRV8alIybNbJEQYbcQZO/cYL6D8rfytmMcjsx985PMVKiVMPSt9WJrF6Sr2f0qm4HM2wPbuvXy1df310/dapOxn9naBrzEjkIXo4fm7kDZn5MKQSKmzfSWAR6ph6RA9BjlKueIL5J1OkCU9KUxstvOqDjLhfaMope8/8B4jfzjGuOGxSlORUI3YyKoegTafL/R51PHqJMwTAxT0jFQ5Iulvy9hpmsCwGmlyZVkMaf7Z+jA9O0+ZxtiOUaJHmoUHxnTUlgaePy0gkGUGy4kd6rOFQgIEYvcHb+q5/o0nufz1RvL1yH2X4SagyiGXBa2kZkpBzn1gi1nMPLgaR3QqOsX2iHV7QQ+4+wyMHWq86tXABx1Yp1fHzvBOb8228WajWoFyya2J7b8KDU4FYv+mo2+XmVDqEMOGYqzo9+PM9M74yrkj66R6R+ZBG5WprSzjIC/AIcvX8F/9WSu/
    admin-user: AgACkD2HFpT3fgN/x8hybZ4T2gLuDjFjlws9Mh7/3WVron6W74RuGPZorhCDmwjpxVF/mrIK9qL4N/IvhHwmYAVkCNw8HlLELNu0Lws4GgyiYv+ktFaN7PGR7Mr3eG6hWOVKLfHnyiyUxg9oQr798LUdsVXnnmKLeny4PnpqG513VcvwlOjQLHCAW2+gLJrSSSvf+HW1uVZx8ygKAkaO3TWKkADJGzkuXTFuXPsmw6nFuW/t5JXtzxlmY3igobPSON7Il687NIaKoLnVRJlSKeIgFL4VEdLPI4FZ2fGa9wpkiIFxYyKlz5z9mICUNPryVG4CQHnOxZlJt6QEfHSDx/Cef6KVUtkx2epTXmc+p61Jj0P45Mrd7vrwT7A6N22W7tqP6u1DkcNfh98ywnJm4ZVLqi2oSrLWU+2JPKQqzQExrRSaFUPGPQaCECVYFHtaiDrZJiEYzqr1QqkUQY/TwVX9jTi3sxbz+agBoSB9r8JVn4Yqk2FL/5Mlp9cKmAegYrRGwvSUg58nbcscHH37KQv9Py+f+m84tHjxy3dJCB3U7+9lhn9tVRWGbotBuyqzfcMbEpnLmx9r/E1l2WDQXwG00eBBJ8VQzEHqGby2MnBWEXXQ1A5YLtdgTnlDDgzVlqKJ1rC31r6gHDc2tcoSvPQF6vx8K3BI4JmjqEpjw4yUg7XXntFdZZqrO10UR9FxOjI4GVS9Bw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
    type: Opaque
