---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-g2net-xyz
  namespace: cert-manager
spec:
  secretName: g2net-xyz-tls
  dnsNames:
    - "*.g2net.xyz"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
