---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gediminas.repecka@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - selector: {}
        dns01:
          cloudflare:
            email: gediminas.repecka@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
