---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gediminas.repecka@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - selector: {}
        http01:
          ingress:
            ingressClassName: nginx
