---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml
  - cluster-issuer.yaml
  - sealed-secret.yaml
  - certificate.yaml

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    namespace: cert-manager
    releaseName: reflector

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/k8s.grafana.com~1scrape
        value: "true"
    target:
      version: v1
      kind: Service
      labelSelector: app.kubernetes.io/instance=cert-manager
