---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDDsd7mNDkTvbULe7kpq06dFLUVqBOfcXns6OloyYXkq8YLvd80tPbPYoBCWEfnzfDudC6IofLj80rWUKgdm1yMuAvvN0xwxN0HTDeSsJcC7e3e/33G1SY0IhUQ31vt+oxy3hpSP1Y8khnt21dFzQTi4Xxuxh0owGKegZTGSRj9Oq1Nt84v2SctdbotdNFgBA+TE1mi6RQXrqnq03BPJ0d8//lNzQI2/qUPfTKVct8PvIs6dDQKMhYTLR+vXD7I5DJ8MWCZSGBxi6LJv/Rj3JDS1PpTpYN1eJhhMgzjJLaEErzCzIo1x9w+pF5sNZRBewPQRM0hDqEW8iCHzgDGz5QMxn6DdnuWhDsjkuYs+ksBhMHI1GFTQg7aVKKDoKQdcoGTtQbRS8N7Y+Y1sWS6tRN7RHg4IHDp3fr7ke5PXvUV9byDav0kljXKrfjsvQWZBBeSEDyAqyEtTgeaS5rPpuBzubJVL30KZBBmj/ab0aAcCVy2TfR0HEaTfdIBAw2Fw1VrRI7Gpt5SuYsmVmKvcfE0sIVrgiYoBwJvSdxqBuh0z6PU0mEq78+Al4rXjjqfouv4rBnnCLoMcy23Ka0QiQfcTIaU1y1NNGNdeaP8yoSexHXBMYW56W67VCPUleYDuZ0fs7r8htNF0vxp2tKNx1rP27dWxwh6YnkZHaHVrO5mhdquBAe9RNZQft3DLqFVnCJDQc+TDrqN5/aVIPgMgSxnIzI+Lu4ohN5vqU5WpDWykx78Krafb2r7ew==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
