---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBQUKKa2xKuLriKH/CLy3UoPbN52gQUj6NuBrQxzoF5Hl1SLiTWl83jhejo6cOLc2Zyc8Z5K2Rbe/s+K3fQFtNVllyGSbqcPCSrTDjjYbMpPDVaDTKSn+SuFe9EDzAJVyeDBW/2UZ1ZQ/9VdV1ffDRLh4+6D764enj4qWwas6lUIEBknOG3U6fRzCRVEJsLjgXcQwja1BerLQPERFzm+2fZN/rjypHw7PpO7xQth9Z4WTeKG/59rtrRyEuAc++HO939OY6764YqV/5Qkzs4W6Ffhrb2HZm5duUq6ufq2HpJzXO2bO+nbQrc6w3KNswxeh9P7P+QiD/cA1vB8F8C1wTtGoKRCbKnu9w125u5fLTeYWaycKUy7hcvkEMAtR5JCwfEobIK6Df4s7HG9UOsaJ88CABZgTYdQRdBn2rgMT3AoafkRL6sV8Q/jBqSUfE2VDqSWe3TDCwbj++0Z/ZuXrp6u+f62VA/tWAtuVE/K9hX2cTQyOwxzgkiprTys0a27vFkc0Z0ZSH+sMJYINDdRH9PTwsxzVyPOXvcR9VTJcQPcriJ3nL1Ii/ladZvErDU55/HY3kYggXgwvznkng5qG0PLqzxFuTh/0/4wHMBMxnKxIIGzbOnU2U3SfkkT2P6+BVdP9sksLVmted+HFHcCg3OSXRa4/KriTxtaDoKcIkhY2jT/E/E485EQkI+We1Uggx2JEkfTS48A+FD9C2NHvhHMQV967TbCtQWhoaVB+VVbxQx7laYeccf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
