---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBYPSuAPWUtezAONQKX6+Yr4P/y/zqocB44XEnuHy/y5LClgp0gDYG1un5Rh/gz7y7kUCoDLb0biMlr2ljP1t+fMlWi+rAYEHWPjgsmyL8SzmF1Ira+Uodmb4P2kVNXUbZxRzVr08DkBNMEPnmwSOlIwjd/zRXplcLSbzH2UK2HcQblNVdD+ihDB6bkIwBN20i6tqQvEKS6FMYu3ckklrBHSNLKYuyBK+UJ0+4+Ng9+feg2/lhxCgt9D2etB/RufDAuU5E/mxy5DF6Fkd524CAXoVKcvDD8ul9TMFdA8tpcDL6X1SaQNaknjNXAnDbdsetUYwQxyNF8vvcfLl9nyxVOcLonyX6aRbjcCaR4y0St0gFHbvl291sqC1upk/0h9qdLdDsdRUOIFcsHmgQmUQJkraeh/ZhIm0HxZpQAi7pEvLZRGo5q75bVPwiGX6Uc55thuWNXaKpXJMSFw6JGOy6UumztTv5QBYbgnyc8mOryHVdkpPjaz+gxz78R682bGPPONiT7pdgf0JVkW5PCqqPbbLAXC0O8FAm6Z1Kdeqgk+pC4v+x/j/kZX275m/w4Iin5rer12fFx6Uk8Avp1JjXO3EubVuAhhnP2+7QtzEQdNScZ8Q16dMSc79+Y3/zGaFFKGUj/0EoXZWneeWvyoajdJs2AHngixgD9gGqybJYlCWZdp7+c1cjJDyCuhT8Nkdxm6lG5Aw/7qqhrfydM2rRQxp+hzly+exPAdmwtjkAlC+/CjrbjdxpN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
