---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCoMR6Rp63Lox4HMV/PQURdwcuDxPegS3dmW6daNTUKBcIwxfFU9dF5oBKjLIJx+fBJYSj412MGKXamVWehOEwL95L5fVVJ9WLFZb6qkO8wZlLOAv27vSb6ihLOMUWmaEy96Ip/aw0SSH/EBFlkaOr+4EmrqUxltfTit7k2l0BXiUBNWlQGN8IKrVpch94udQZsl3gQVo334REfm7Ah0yegLpwrAaEW4anQ+oLwNGXXTf0ph+qPjiAGrUnQuviOhlk4eahyj5nmYlUU9nfMTPBiIeNYdpMCVwUabe55KGV0jJ8T5MKog7fhLeC5aPx80mimTzHZkxbZw9F+oiNozY0PPpBmupPcQcrkdoFZlxsbwHmieG6FrH0Clc2ZmAgPVJ5bheTa0iXq2gjTrlykSYT+tCGMNRooy2+CwJA/Yy4RRVOuhi9zpfy10K8hDcxHdbTkBAhgzW+3oJumfL1OJi6vY0HL4X4R+wB5hKTlqBiwmqqCdEMekhpiRIEB+7lYTxWEsgdtbCb5DhXagiCFo8KcHhhaJsyr/hKQ3CTz/Sqsq41pPjdjdPhV+QZBdDABCHk7jtwLyaDyXPgTQcGvSq0rffZLhlC+O1pjywCTkdeAOIa/xRo2JsS9S/kyMg9ARbbOtpelVPwEKdq3CFn+D6R7KaEFjcgV3TK0uyST6K50S84PZiQFjrfYo6ixx5eL1K5v/9cszKgvGkA5KNc0H6BV1kvOAHk/p2JojNXKd6D1E6K2hOHCuJDf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
