---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDcPHUK3IzhM53D0dpZ3t9tXBpSQTyqNXV1BHb00noY20795QKJD5p2yvFBvMQ3/fNTwxR3YfRHkkqe/P1o/PBfv6LhCXSDfzZFB+Pmw9tW76FkNb+WNj6H0+WrJofCzQY7IAORExh4ZLQa1hY4jK7dNnvEtrEClXmpaEuUPmI046KVHKLcRei++HFpw/1CVrfZINnakIE0BDx3kQOM/8VkXPVq3YPjF0w25nOugK7Gtjp0rvucH6f6aXkT3wqCLHTAHEwnQYgiYrCmCMt6OUZRBj4tlVgqNbweN/C18jp5ty7VauM1VnrB1sTXPjn4LPmyl4AjA5szh/vwFM3GX7ZoVc8zUMpm0eFxEAeJd25b0PzOk2poZZ7Nt+D0OTSBNfHzC8KTgVfHPPHcazq4GD7zGX78H/fLFqNxE8avBC4j7u7eGuZeX+XvPhSlP62JLomkrDM5ayc87tzFAMEZIhAevaeJoKRPJLsrMcuZ7J8YW/s7rs+k3Mp4Njr6eLbBNeoDQHwGYR1Af6Ox7p81zBlCrdmEQndhfUkswadjaOIJsxBUyFnlo+nTjJ3aFV8ZzpQXHGDDCnXWxqvym3b73b3Rvpt3AOG2mQYznz80tdfDGosJVZILqU8HTRrgATrOSGuQ2Awcd+JBWsjZSYFHYbuRYF4vfXxfKkrxIGbNkXWLw/eEHi8mp+e60YfZGJ57Fjd3Dj6pZCqSUfpFgWzsNzbVvcEDDISpTCbg22mEyHx/ArYd4Cy3FM9r
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
