---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAFB6OHZP/3mrj22hnRBtKTnkAUm1oYj/+SXdvtwnHKAc5M7oqVTL6tw0lf+MQo0rnqtWpAdEI179+9dfNCQOiuBjnf7gFSe7lJzq+vzB0V8BozCfJ3umjS9XARFFjTq1AoL6v5L8q7VMRyb59AeLMFvY6NRdGOakwC1UG49UM396bm45akdZ/NY0fd9wx3kZ9bsx1CqHIgGug0jTxC38u1NwkMz0WBnaeO8WTn02ovXEOLiUt04bGo6VZ3fk7JV/EokjNtaem0AF/4Y++GvQdOM8G6GQ9otG8lFFgffp9COp+Chtf5GXiLB2IO15w8nAfBA8GNC+ypXWkzQIdE49tjGdLQq0VdLhnyb5r38ZAz1Nwd4AYR2g88BzvosghzoiPmvN4a6RvDyZH+lWZmBPd3MiCNGbqTwSMBhqYc7+KWkWoBoJKFyiiVzZK1BUsgLY7taBsT5g0vskooZeNam2gAzWcmKqfDRXVQPghCMOC2ptrzt+aH87n47obS30OunYrruiViCn2UsHrPXrEhvlDxz6ek/gnJ5T8Bo46K/aEP57UwfCAdN4/QVMcEHyuG7nsvq0Vd4WNtH25T0ImHD/s89LpN9GMJ9tvKeMwR6a48rYi3AemK+/PuXSCUlNv+ZSpwuE+hN5hsirZoCJIq6sXUl73H7uu0JjZyKhyJ96l/jf+b8VAbCI7mITHebgIL5i/A0xuztk/3881bnhwi+/lbTzwQTJ3vmXVEqaHz5uTeL/d4XkVFDr2H
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
