{
 "title": "Go runtime metrics",
 "description": "Go runtime metrics",
 "tags": [ "go-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(go_info, job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_info{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} (avg)"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "timeseries",
   "description": "Average stack memory usage across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job) (go_memstats_stack_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: stack inuse (avg)"
    }
   ]
  },
  {
   "title": "Other Memory Reservations",
   "type": "timeseries",
   "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job)(go_memstats_mspan_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: mspan (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_mcache_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: mcache (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_buck_hash_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: buck hash (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_gc_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: gc (avg)"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job)(go_memstats_heap_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: heap reserved (avg)"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: heap in use (avg)"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "timeseries",
   "description": "Average allocation rate in bytes per second, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (job)(rate(go_memstats_alloc_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}: bytes malloced/s (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{job}}: obj mallocs/s (avg)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_mallocs_total{job=~\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: object count (avg)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job)(go_goroutines{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: goroutine count (avg)"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "description": "The min and max Garbage Collector duration in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"0.0\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: min gc time (avg)"
    },
    {
     "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"1.0\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: max gc time (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job)(go_memstats_next_gc_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: next gc bytes (avg)"
    }
   ]
  }
 ]
}