{
 "title": "Power usage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Power consumption summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[5m:])",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[1h:])",
     "legendFormat": "last 1h"
    },
    {
     "expr": "sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[12h:])",
     "legendFormat": "last 12h"
    },
    {
     "expr": "sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[24h:])",
     "legendFormat": "last 24h"
    },
    {
     "expr": "sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[7d:])",
     "legendFormat": "last 7d"
    },
    {
     "expr": "sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[30d:])",
     "legendFormat": "last 30d"
    }
   ]
  },
  {
   "title": "Power usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "shelly_power_w{k8s_cluster_name=\"k3s-homelab\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power cost summary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[5m:]))\r\n*\r\n(0.205/1000)\r\n",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[1h:]))\r\n*\r\n(0.205/1000)",
     "legendFormat": "last 1h"
    },
    {
     "expr": "(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[12h:]))\r\n*\r\n(0.205/1000)",
     "legendFormat": "last 12h"
    },
    {
     "expr": "(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[24h:]))\r\n*\r\n(0.205/1000)",
     "legendFormat": "last 24h"
    },
    {
     "expr": "(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[7d:]))\r\n*\r\n(0.205/1000)",
     "legendFormat": "last 7d"
    },
    {
     "expr": "(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})\r\n-\r\nmin_over_time(sum by(cluster) (shelly_total_wh{k8s_cluster_name=\"k3s-homelab\"})[30d:]))\r\n*\r\n(0.205/1000)",
     "legendFormat": "last 30d"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "shelly_current_a{k8s_cluster_name=\"k3s-homelab\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "shelly_voltage_v{k8s_cluster_name=\"k3s-homelab\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}