---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn

resources:
  - node-patch.yaml
  - storageclass.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.9.2
    releaseName: longhorn
    valuesFile: values.yaml
