---
defaultSettings:
  createDefaultDiskLabeledNodes: true
persistence:
  defaultClass: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  host: "longhorn.g2net.xyz"
  ingressClassName: nginx
  tls: true
  tlsSecret: "longhorn-ui-cert"

helmPreUpgradeCheckerJob:
  enabled: false
