---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.31.0/controller.yaml

patches:
  - target:
      kind: Service
      name: sealed-secrets-controller-metrics
    patch: |-
      - op: add
        path: /metadata/annotations/k8s.grafana.com~1scrape
        value: "true"
  - target:
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sealed-secrets-controller
      spec:
        template:
          spec:
            containers:
              - name: sealed-secrets-controller
                args:
                  - "--key-renew-period=0"
