---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

resources:
  - sealed-secret.yaml
  - subnet-router.yaml
  - proxyclass.yaml

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    namespace: tailscale
    version: 1.88.2
    releaseName: tailscale-operator
    valuesFile: values.yaml
