---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC+uEeRf8yEYlZU9krsr6wJMncLdCrPHGv5Fn6s79j1+GNpYewFzwNVCbd9vd/Ksl3dNy18NQtOzmjKOUBShde4XbeoPk0ICsz+u9VlaZ2D8AcatTXrdvQrpwhMUgHVYYt1M8mdloQeFI+Q2Pu4fQ3qm+2ID/ENNOoVhls3bjP/3H2ByQg0pW7dLDg1AOIxBzYRIxcs6S5wLEvT+NcW76xTrrlKnOlFpHVx085o6eAinrL/lAQQlEyM1irtehDNeA5MzZtwVJncwjCrO1ZmMTw/tjweJc6puIf31hDykESPJJW+gNAK53/uuVjymH8zo1W1xCRS8RBGW8pEyi6drX4ctOwabt/7vnTT4BhklwwZV2TK+oSJF1qI7HN94MnyvKqWGQRYXZxKfB3DN+r30Ksl7jrA2EkIZfbSo+qXUJPooJhixTKJezLs3wB9oSqcW+KdH202/KGUSU9J2F8j4vAgREq+SD4JYiXSbWhHsc2sdljDIBtSSLyP6tChk+s0EBYkd/foD4fo7Fkh+BTKU+9yJ682VHKSekGz8APacN6zgdGbHqkIVegnK3TArYEsIRdqYe14ToVE+G2L1266TP8LVbmixpxCGeoZk9ErwMcqn8CFJhmd0lTUoJXtWheRfqWofrPFboX5nmFMWO2grSpZGcJ24CdyujoASx7aYtHr4OqBX32AQEQaCtxHCYdK9TDEO4UPTgBKimZ3v4l+Gv41UA==
    client_secret: AgCoibTde1SBP8as+gCXl3eXv/OF6qoTM7ZYI9ZfCkb4jZNn5jveH6nuA7pXUASm234Ro4GEHtQX3tz3lbIOcUJGWRZm2OQ/lYou+Xw81ckzq5aavF4vSBGXTz6fFMrnvDfdhOdKzuy0HM5s9NJCQJsIFdlZ9bq5R0SAsYp0kHXI7TrnM2trvbDnSwa7NMSbIrjetP3f2KLBaSnw5cRfKfM3Cxl1GiDTIzXMcIg1rio9Fwsj8L0nRBf2ZXw1YyYshQC/SyDTJYtyNo8VHpLLgDQZ40ZOdajoupSUGGzdfAABzSPjdTqoYfueH2w/vQiRAWKAR2lusk5PqwLlRdr0GlLWW1l1zySEEM0DZeomEX/HZGHxohIJTLvHHgGrhfyzm533OKF1sogHTNYZcvrFVDu5+MnNhnicjDOj7ifCrERp1AlNedYn0AzWmyvDeRbpIPDWzC+qrjDnPeAmf7RNsdd5NOLhRYkhe2ZuLwOAl1hacy44eg6VxXeY8sLel4Q5uoECzSSLD2dsPtaGDgPCfQcquS4yv9Bte2ywDAMwRkQyQWYFJ/U6mY5SAfKW2o/ugztV6xaKlW821630lB1OP0oiG0dFiGQJ3R8uDgxXG8L+gbNF2nZjy73go16nyjjGmZu1+O47RnDWgdgdNRjOpe+v5caLbrzF6hplMHlslX6dA/CdqPUVTclXGJBwR0DkzumQeeH8od53sVVeuP4mrL88VyWzTO7WSulnXjUQZnCY+4S5zJfL+Eo4Jnf4Gbo9CD0kTJ4mE+L/EvXSCqGvaACR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tailscale-operator-oauth
      namespace: tailscale
    type: Opaque
