---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBvY6RQKOLi2Pp2zYfi3xSuQYp1G8xEXnF1p9vUJtkaluavijyBG9x8hqfdmROxm+wTQhwCb6podK4o0qQqaKwP7cYzvr3rFpqDkDl7mpbP7R/L7+ebdb3+yZOomN7cstUdfssmqIV+DOucUjsEJB+ADB0Vly7ioQ25Y3XWPCEUzPF1jooAFwrFqMfoOWNVTh/xC9FoNdPMBAXKqHGZpxgWSs5UAUBDoEUwSmjS33cELiwxhj4RHw09CWilS+c46Sy11rpc3z55DqdDPcLBbrXXsxLRBHH9AislrMb4XsqSg/SkKx08QTV/67eXyuUdgco7Unfe+ycv0I4v1OWKRt0xJ3GJFaQBVJVu/3LEHRh3U0pkAEyrcyr4cjj9xC30mJBOMd39wHRhzECFX2KxhiL0gzRGOnWMgMUoJoKGwAGIRIyh+637lcRVeIHgSKzQf7/VTzbo45+07qmspNgcKEh7G69HueQ4hUjb+gTm/Wd9KJMW41cZZtzjbA9ViXhhIYxWNmOy8xs75vV+2o2IohIehqyTzBlrZWv6v76iz9BnR8XBxUBDWoNgwh3p0jdpxC0uAJD4DgJ2H9OWmv/RU+Pc4n5/q7/8aeBzkp+lLSptMIouVmy4YuMzbTDM6bd+B7Oitvn3qAY/4aMHx4xtMUADfwGGFOx02MnUFjsVu6A5RmpMXDVdevJXzCv+XiIincs8zHFzfOt6WZn5WFOdjoeZSQ==
    client_secret: AgA17aFvP5DHZeMz3CKN2ngLorFdawqzpdobK0r7mapDpdRVT20v08Ok2447qFaynSeNRTASQne+YscRnRsw8WsDIg8KUjsdJVErQhG+JyYYZ3WcIOKenTksdqtF5BHV4esxp0HKB0GikdItR3jOyInUjj1R/DhYla7jBcs0/+thZy6m0iGGh/ik18hkiP3xk4kSB6Yr3ekXYeH5dUK9t4ky58Rse2ozrsjnEOZcgSI35GQf8Z4Zue2l4HDKev+XsQuODyh0ybG2YuGTCuW+idPYBJeSgblZNQBGcMhllfpm7crevPz3WkBELZ0MNqYUPOj05ONJQc6go+MCaJp8P+fYwQFw7oxLwUEoioL2/b6qCKNZBijFZ58Hx0HTCLZC2uSRUzAE93yt8iVIuE1c8jUKceTmGUouV0ggCFOuWgNikNRti9ASfwC8GtH9M40MTnIXEnxlOr5YGTVV0Z1zAm3VfvBDalENWCzxf67XVSqiJUQXdoYdUfbpqiyALE2aGkpeynnr1qlpz2jGDlKhv/v3X3JCuKQfYmF+pVzP88E7WG4bWWtTRjmwfKOBp3UZE0EL2lAMgP2UiArj4LljDS5l+Y6zfYaUqUMT74ezH6M8wWpbC1ONnOhDqYpCBrrPMWIwsBvyoBlS6Ln7kTdR7qf5BktwtdU00y0FNitRkm8lYUoen067GreB+sv0/UxyNRrodj8y9F/EYYjqVQD1zRiePfgEQJYomMx2RvVQ7fbDLASOk8dbGLceP2DrbBeb25I2VA6ucuOHA709WfGarDui
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tailscale-operator-oauth
      namespace: tailscale
    type: Opaque
