---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgDUZkBVHlZGiQxiIniPo+sVPHWz2gauE+DKZO1VRelPZH+9mbi0KDmLGtzzGdy3d/FLYyPgTwPX1bEwhuYlR+AgC6oQxZROC9kza81DU5CicBgGxGI9dvDMXiN7PTu8fIMH5ZcHbBEoDMaNIitFN3SZmUOEh0H8cPqq9Qrt+fNA/MWTKjIXe5vtZGTpyQgp1nFkabQ+2f4W+CFUfo6Rup3312JwJ6ub2oHr0eJ4HMxO3bjjTIy92YbOCk+M9SD4Xib/pXDWdd9sQ8kCQzZ827Hj9y7iKQK+AqnkuWFHSoxnkOI1OmZebWI6EHYDxgD3bRORzTqPM7dEZXe/gGqKOz5d0iTxGYT1WILUnDEjlY3rKTG05fcZlg4h0PZpuhyvzb08e8SfQPw6wh7gdn5SxpAP7mJLqhhP5hKHSleNhea433wCwxlk4UtuiY9UtUQeoChi6Vhb1RKLIeq0+SlWsYQMCtFidwRaiOaHfWMaFdV67QYkLJ/uuwowXtXIWB3NDE7Ab3w0wXt6TLM+tw8z7xsROpjKfbY4bSyD99YSQFQwCxxWVTGkHWzR3RlAlA501Ms/A0J90FuePFMhUZCSIdwJuphOEqa60RePqc7MOvmNekcOAmEz5Ta/VCMNb7ea0Adt4lF6KttVP3A7OzzW2bPDdwvGlt+ZYcW6CWkXRmeeQdHkzyl9MRwacGVuWSsLNfq0mUQ3cU9/3yBx0T3QErjOzw==
    client_secret: AgAg+GrmRzPpvQVl8/qt+w5/Vh5YbeNwGN4pMgArIWFEjbitHdn2bHRLQyueaeK/V/A0SLVhKImUlQxevjPJHGK7AHdUuKBVJjbNgeX3xqL6ZLE3yyOjCRHuHwdhbYr6mB5HKyQaK293ekmKxN2CPgZ8vIcHabCm0KVV+Il/hGXlIyo7mT1W1yR2yyWUOfQs+oyJG/djFkmDoD/80ypk+kEQ/HkH7AlP5kdBQiRt7P15v9VQ0XT5Zp04i/NdXiy+TKV1+PHy8zAE7sKiKSO+1nzAiPjTBnk55/9NHDyoOUHG3kyL3CQXFCGPC3b6oPIL+iE2oia+PjpabhriE2U3wYNSZ+kCzhhqZTQU9s4mDj28LrxR6aq/hIXLwSS1B91PxjjwZuwIiOErB9iFTvlGqFos2SWTzA4PQdaaAplYe2erbGS/nMoUfM6Lb1Rg6S4LIlM5FnTWSaG0zjGqe2Gp41/o4/XrY/UMg1DTtQyABxqZwiD0PB7cBqumoSZxYryiwiROw1IjX4knQgjZ18QRdXsDmd/UIpgnechgl+d/j29d/uTPSpksD1D43qzycb3NfZBgWdkjhUrKTWp+Ji1IVWm9PNzitsky5FeB3NYYeEwNsy5orrsDU392vdv4AUEaMA9SKBOUKLTYvPUsH9Hea6DEHdvvxygzxbhHCVRt4y53VBzQrpVm9IFrQZ/5nJWuFj3bAw+R0YndcMcHwe64zp2/0bSPi+7fBeLmoj/5niVEea2vZzrI2NkbLT9VYuNRR/p69Y4IJcxD+tG8i1Yd+UjN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tailscale-operator-oauth
      namespace: tailscale
