---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgDgfAWqF4Szjr6Qosh/qKOPm6SrNIYJj4omNYAPB1Xlw4hGfFy/Ps2YY8U1HgUjmkTA4HQ/5kdM0Kr/4dbAw6RkkcFyCkLDh2rclbgvK/mQbw6LyRFAxhsmjgCl9MAcEP3NfuXOMxBmBNdlycUX1xeP54N+CJrt23Z0dBAVgbszyHQL2ZVwiZ9WAvwKliDPC8ZAH467i6+xwhUxZ58kN75oDhJzXz2uG7a9iOIG/FGppT7Ahzl3mQN899vn1ApJjoCFRvshrUr6++H2RddOZufV9T2zN4JiWvzUEuADYm9R/GZcFAAzNP70vPG57bySEWOMX6A94KxASYWzZi2JwKBhuO4t5t6dpGsaeVRzNLV5dp3g+D7w6zoLTjz2T2sb224BOjmrEgXUnQrexFsWZceUIoftZQi6Xv/G2c7dg+iMh/mEWIwTW1JvW1RVSz33k96jVb5GwF1FGwqsWtBfQY8mBlDKKzeIVZ0JbTpAz9RGFxu7UDFrI8VOBRbKPy6fi9aTr/fFn5xG/fhikXNGBlHKwQQ+nzlNm+QMAZqeYQdCRiR4+iHpjNO9sgWYYmUe/mzVDaj6mF5yZklJUMA1tBWjnCxldpXgx9ZNp3eqmA6T/3HzvC4KO2zM2o+V7pgSZW8pG76oEl0Uxu8YSwWeJHsIN0tGahVLwmh3mNVOqANvkY79P/MdnBmGGmGPeaonIBg1LzRvt3Uzt8WGb5D/AEXeeg==
    client_secret: AgCmH2ld48oU8k+n5Dqabb3wJIKrVsCJ93YwedkZ3w6D+TZY0nls0Tka7TGhuT9sIeaSh+lC6OcFqSqyMz7LaaUl8swI9oAeWrzpcS73gUy6k4MDJBKnoRHal3geWH/MDzikMg2Ik6TJB5m7CFHrde2UOcuhEnS21AIWlt/bsL75COMZXIewOEtH3zR9EhuLtFfUF8OEwb5eicdu1+J3gT5A/wkd6SURrr+wnIfuCyZI2E2aitwakNjxB2z2BIkslOfMM6/tQnRjigJ/OYYcdbrGP4PrenodhpsBrJLwoPoIEymdKS2L91NX+XK8OnHNubZEz2vHYOucPDugH+vjSmbPkYrmApkqPgtlFhEiJ1ZNCEcJ920LMqYFhfO4I1APJdasJi8IEdVwWQ25KyHwP5qehlzc7TXrMGBey0U6R16MrxcthL/FFB+wcZ/vG1B8Y9CbSqJWtudXi7VBTgWrN3HlzkwgFXAEeycabzJRU4eQNEdVtKFCWG2sq68FH20wT31VrhQY59F8Pc0tDZ6IGVfOvUXotTIRtDcDkXhr+OG/mfK0tvs1Ex64tFRSD4R25iXqe2gu7ZFSqswKhXQbe9a8ihWlELRY7EHX0OnXT9u+U/pNhUouNJm6vMNqp9RU98MHBj8xsywLKYsfuf5e+RHkUP/R/9LIJXD1HWV7j9HmxWJddUtZ9QP1QDHMLQodxWiL4mQUXGo30pjluBcZ4veDRNTT0NBErZejGr8cwthaVWdRYek4oHQUmy6NF2AImT9a5icMSrGicY4EwOE1/8Eh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tailscale-operator-oauth
      namespace: tailscale
    type: Opaque
