---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: immich-backup-schedule
spec:
  podConfigRef:
    name: immich-podconfig
  backend:
    repoPasswordSecretRef:
      name: backup-secret
      key: restic-password
    b2:
      bucket: g2net-homelab-backup
      path: immich
      accountIDSecretRef:
        name: backup-secret
        key: b2-account-id
      accountKeySecretRef:
        name: backup-secret
        key: b2-account-key
  backup:
    schedule: '01 00 * * 7'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '@monthly-random'
  prune:
    schedule: '@monthly-random'
    retention:
      keepLast: 2
      keepWeekly: 4
      keepMonthly: 3
      keepYearly: 2
