---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  inheritedMetadata:
    annotations:
      k8s.grafana.com/scrape: "true"
      k8s.grafana.com/metrics.portName: metrics
  instances: 1
  storage:
    pvcTemplate:
      storageClassName: ""
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Mi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: immich-database-1
    namespace: immich
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/cnpg/immich
    server: 192.168.0.222
