---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    k8up.io/backup: true
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: immich-library
    namespace: immich
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/data/photos
    server: 192.168.0.135
  mountOptions:
    - noatime
    - vers=3
    - soft
    - timeo=600
    - retrans=5
    - rsize=8192
    - wsize=8192
    - lookupcache=none
    - tcp
