---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: immich-admin-api-key
spec:
  encryptedData:
    API_KEY: AgB5biKVFHOppClI/MTLZFwYkAn6potbnYwmDyXRPnfFGfvkTfjnLMkBvQyw8r+dfmEi0F+QK29b+j4ZL0ZTZXPZ+rn2r+LN94SjQea5TXcQc0UgaGmpC3vJYHqLuhjSivN2CLK1khkVyUptuReNtr8RGT8kfoZwtR0d+hj/1cuq4QvIXKE2ROQmuguHxvwM31y2srdwgdcQpd3TSIyZ3D5LvFuO22HBIHODrlXqnkBKxoLchY67QTYnTnC+ObGYdVV/uy5ObJ8jSEiHYh+MOYME+I9N62Whg/vyRgkjzcQFdHketKtsokL+X62aV1rhTc3rSl5NgwG4FF7+etPn8wkwu/AElV1kGgLfz8omdZBQUJS82mijGWjuO+pIcsry9XAAYHcD2EyxeQQ5G845/enQtbd3OOcz49t7EPs00zTf8ykgoFA12zW5s6kF0BJsUwP7QFNmvsBYfbZsslePU5VQC6vSmlSVMQ0x1l2sU5iiEGBGhCU0rIGLHG6Wlyp/qweu9slHOt3J9getBAgh7smqeSlNxvIl6DGJWgS7CYCcZh5yEnQryxo38viJf6aZczBcybe3QJWL3yn52C4UKuYlCyQM0A4PfKApINaGMLLjV997c6AN+IRtzNjdqsI4j0ViWXLcq10n7PdRImzw4tcSZCisRVY5WAkVI7l2xoDbXKOgFhBw7CFUsd172HJe8njyImuGEPq/R1wY/Wt5zlilVLfgwquCKicVOo9D+sv5YgPjIxblzb0Hr534
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: immich-admin-api-key
    type: opaque
