---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: immich-admin-api-key
spec:
  encryptedData:
    API_KEY: AgCvzqFezUazff0x1q+igqQEwIQiRVLq71RciLWnxYdsH1JrBdZPgXK4NAEJGkrUck/HOxmzMuGjqFu+JhiDcBSoddhDk0byCExQlh75vC+2NFg4/0GrZx8BuHWIuCHXXKBy1TVg0NWkMMFjANyG7nsuuXVGeR7neRuJGqjz8pUhsOX9cDyXxT737Wisszn+lLBMQQBHJaAr484FBoHFL6ivS/Ol7fJdUnjDto7PeYfP4nx+SZmPZ3udRxMGt4KP4amygYqiqfF1X/8rosz1il0lwblTWRmpsdBZNw5ZfucOzdPLS5WGt0fNu+Ndk50gi52WIFvbUza75FSG6vG5ntv70TmN9ch3XV5QO7ISFGJXISsl8GDF6mDa7zXyvanq00NwFMRMo4alXKgrxsTvBN3AkNV10l2ga0vbaGptDL6DHBDBZg7aX6hsg9Zyy8az9H2Dg/imTGzeC7Mfrsy8JshecUyV9DgUrDV6NJ+jlO1FIpSWYx9OSQ3L2E79TgLrN94hD7Vn0sFCCMhDN3UJ3oOd1QXawB69v/shSzugXCk3UeM7nu4gTkzlvv6ggatqQHmmFNerXFFz0Zvo9XsKOy5nNojKuuL47Dlt00p8cKfD+Qu+Yy6N/wHptEAKAimLuC+D1OlyLEHjcJh+LxdVrjBvbUl9rQkb2YIJ4wrXCuOHuuq0NjrjfzFPiVvmhp1KR3ErGkCgGn0RQYXH4Pej75b31Dt3ghw4H8H16KhCp8g2hSLehV2m0fzN4FNx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: immich-admin-api-key
    type: opaque
