---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: immich-admin-api-key
spec:
  encryptedData:
    API_KEY: AgBAdoBcdGWAw7wrNea3tUSOvNpIB5HkBAQ+w59oY0OvpNnYnsfIISmPSdsRgj1N10vNIRo+7Lbpk0fvQCna8DhqSU2F7Qu93nOEtg8aCuEy3aLh93tVBPhCw/VFSd8xxaz4WQ+L/YeWxHVOEQMQtaEEYQgddBGJ+j3diKJytOZ1yXoihav3hKGsstd+rxnq07wha9Lp4pDJ3HUkTZUUuwNwt4IFMwijNiScQGX2K3AvBmcVFymaoAWmJk9HGO7QgyaDDgX5lP0jbpsH3YoHMpr3/aHgqPR3WRd1p9J5rGRQSKaAeijHiCTY11qiww4ddykhWEu2PR0sVsIgH/waRYVWRzBO/L6ZVT4WNbjj42Bu166T78R7NBIOUkoHrF3R1x5TY3+mwJ3fvXK7+oe3zB+ivKNqigag9wdQFwFqXLfv4F/35q9urDNG3JCwal5X51BsTwNmw1OqPOhACnQ2Ltz5EhkjsPZhpYnGhpFpqhtar8OTGwo5Lgblg3WiFpGlPNP5dtakWNyuQqYAgi0ij12A67f19Sbu+/mShOdxSXIWEro3pXUba37kMSDXbxkwn50TsIfQOelCg5a8j7AMsD90Y6DHTpMkI3yl1mQg9ldm0a7L/DT8MdLBwgLvPctRRmzSRNFX1GXj8Yug4WgZ79m/SZms/203MhgkrfYfqDu7dYpXDHmlHI5aqbifmVBn+UlXrDwdEyAenZqUkyGg7qjlASQ7a2L4tO8m1eQLGUN2QPStRV1e/jqt/tkm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: immich-admin-api-key
    type: opaque
