controllers:
  main:
    containers:
      main:
        image:
          tag: v2.5.6

service:
  main:
    annotations:
      k8s.grafana.com/scrape: "true"

immich:
  persistence:
    library:
      existingClaim: immich-library
  metrics:
    enabled: true

valkey:
  enabled: true
  persistence:
    data:
      enabled: false

machine-learning:
  persistence:
    cache:
      enabled: false

server:
  controllers:
    main:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - n200
      containers:
        main:
          env:
            DB_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: host
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: user
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: password
            DB_DATABASE_NAME:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: dbname
            IMMICH_LOG_FORMAT: json
