---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: pyroscope
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    version: 1.15.1
    releaseName: pyroscope
    valuesFile: values.yaml

resources:
  - pvc.yaml
