---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyroscope-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pyroscope-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: pyroscope-pvc
    namespace: observability
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/pyroscope
    server: 192.168.0.222
