---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: opentelemetry-operator
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    namespace: observability
    version: 0.110.0
    releaseName: opentelemetry-operator
    valuesFile: values.yaml

resources:
  - instrumentation.yaml
