---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: hermes-agent
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  role: Editor
  name: hermes-agent
