---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: itarmy-identity
  namespace: itarmy
spec:
  encryptedData:
    api-key: AgC2rRL3tGCJ/Pt+B/Yi7e6WiNOqdzqLktjv9hi+oMoUVsESzK6LV0YYYrlrwD9/OMLfiw+fc+XFk6ah/13y4P/GxiTqYvKSvqw7xNTUgN7yvQlsFDhLAIZdIaR8sWLiFxVYFBKOLcgwa+uWYWgs7CVK37YlZfmTlKorUPBec0F3PEPW7jUmj0N0u+7N4ZFF6Z7Tw2xTuvNZLstp9lLcldCJp9OKWIQWnlibtQo8q3gFRSW2ZkwqzwfIiHLQCcAbGhIRaeSgs/d1Csm05OJh+iShBBcSduUmsEzoz+YvQ/TQrrm5jD/nnVCiSqvZStR+eS5IX2gr5k3xOV69jclJFpW92lWryjR/iPBMY01CYfPApQT0vqqXXInO3LG0lRPpBNSR8iJ16iIBXUA0AJhikYd3iZQzOnUoBV2ySCJJ1PrI2Egc0QgP1b8+ZQunhU5xAYUJQqOcs9+QOch0BNPnXzrMg8TnAOYo4BVvZZpdjKRzJMGkNdZ6lvF268Qug99VxbfzKcDHUnlPZ2w4BBZmuct/aVsX6F9HIn16+Pomh5Wc3ButFrbDe2b1NKPF6ui53LCSyh6VOZWpkS0GhbneBOsGk6GzCb8crDx/g536B7CBWS+DLz1PONFoZdNt+Sgt9axG0/+UQilWVIrVseVwmcjtIkW3XRqFE+gcMDmqd4rCQ6n43g/YooKa91t4YWVQV2AAheclLrOFXMiQ/9dO0nkEfoATp40A8rDfZJtn9Zs77RQ/Uu9LgmQfR76O/Pf+pbQ=
    participant-id: AgC6HXCyCrYvNF4hO6rOnPzzSkOrSRrC62ISadDsB5nroh818cL7oqxdWqTlUQh2Jp/zpnxDrMbBN5F7+EryQBy6vmtvJLDty1VK7vpNGgJVIlzGk6RDx2WZycsr/rZj6bJ4Q5+GeiEyrWMMWotVWogkQrg2gSLkGI11HdwtP6NjaK87PD1Ur/BR5vXnk7zqoGcODo/bqde8co4xeXqrEWHfPyxY2Ngy7q11evM9VK8Zcw6sxRHYEel5FcKi29TIMoFjEb3ngTTlodvgb+zl7o8dCKGybM3xlOxnk2FAKaZ/h6IFzfyBYBIthB2R0HdbSPdQwj65axEvD6rgGF2Gt9KQ+yCM7kWlj1u06n28D6Njr+PyupZgLi9VsCjuPuFgqn5H7fDb8gvaodoxxCOHNWcqztZXRSZMt9uO7VXF4qSU2Yof+MIBxf5SOyo9ETKzmtmf83QjxXo2Z0CfD/odLtn8g+K+loLzzE7L1UlLyWE+divuHLHVXHDIAWzNoG8ytrmMqU1hqYJ1x7vJ6/bGcs1KoGh1Jzfrbm1iXP9SHyhxwnXQUeeWsSMKJLy6w+wFHyE/X98bAPJYtzNxZ4UCPDhFFCokGYu6tk1MetqkiXGchvGKIghBi2pSjnZWT7ef4sdVJwlGr4Ty84NkwADmYGtG3aTrwj24nSJB+kghOHaj52tHwgYKaGvTw5DEXu9Q6RSzvZZTXbTX3KhhPFikOiRQ0Q/KqD4C34PRmFVzjDMk
  template:
    metadata:
      name: itarmy-identity
      namespace: itarmy
