---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    version: 6.42.0
    releaseName: loki
    valuesFile: values.yaml

resources:
  - pvc.yaml
