---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    namespace: observability
    version: 18.5.2
    releaseName: loki
    valuesFile: values.yaml

resources:
  - pvc.yaml
