---
loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  storage:
    type: filesystem
  auth_enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

chunksCache:
  allocatedMemory: 100

resultsCache:
  allocatedMemory: 100

gateway:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: loki.g2net.xyz
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - loki.g2net.xyz
        secretName: g2net-xyz-tls

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumeMounts:
    - name: storage
      mountPath: /var/loki
  extraVolumes:
    - name: storage
      persistentVolumeClaim:
        claimName: loki-pvc

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

