---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: maistokainos-aws-s3-sync
  namespace: maistokainos
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
          containers:
          - name: aws-s3-sync
            image: amazon/aws-cli:2.31.31
            envFrom:
              - secretRef:
                  name: maistokainos-aws-secret
            args: ['s3', 'sync', 's3://maistokainos.lt-scraping-data-processed', '/localdata']
            volumeMounts:
              - name: maistokainos-pvc
                mountPath: "/localdata"
          volumes:
            - name: maistokainos-pvc
              persistentVolumeClaim:
                claimName: maistokainos-pvc
          restartPolicy: Never
