---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maistokainos-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maistokainos-pvc
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: maistokainos-pvc
    namespace: maistokainos
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/maistokainos/localdata
    server: 192.168.0.222
