---
- name: Deploy secret
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/sealed-secret-key.yaml
  tasks:
    - name: Create sealed-secrets namespace
      kubernetes.core.k8s:
        name: sealed-secrets
        api_version: v1
        kind: Namespace
        state: present

    - name: Apply manifest for sealed-secret key
      kubernetes.core.k8s:
        state: present
        definition: "{{ manifest }}"
