---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.0/manifests/install.yaml
  - httproute.yaml
#  - apps/app-of-apps.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
      version: v1
    patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: --enable-helm
  - target:
      version: v1
      kind: Service
      labelSelector: app.kubernetes.io/part-of=argocd
    patch: |-
      - op: add
        path: /metadata/annotations/k8s.grafana.com~1scrape
        value: "true"
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
      version: v1
    path: tls-patch.yaml
