---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    client-id: AgBxyWPwSoi+BHwdxGicr7fvz56l1uWkZ6dDIEkQG+VQo7GsIugRRIqKX61o/S1jFt2bqBd0weKEUPeW/+jJmuCaMJU/zuFl54jNXJgAhuR/n/dyY/VQsTIRo/1BCuJivpBP8E4tM4ypOTLnmekz6+nse4hGIvJdGgqpeoYGBpS2PtysTz4cctJIl8WvIoqGJkOrEUyxscyfs2dzYQOsDBjzJoaYHH1wZz4EKZDzXFwVfZyWXKg4dT2Nf9bj3o9a+ATsMCutKVSOVaa99ugkRWbqwB37JsuHUhX4PokMgvoiKDpPFL9cag5XC7aoeOV90buQqagA51s9ay+krvYqmB7tZ0K5GVAI5zRGrTWFQaazQZCdYX19MIUVhhrE9brSQKQlEzbkxSj1mf2sKusIyVSDfJRq+o51msUBKYWnlioqYhBb087lgSCSpDKT+a+xyyda/TmtKNiVzA6tdPpqVj4XEdSNlTKHfZdywzkrgBa+PVsMK7B4Mm2ICOUv6pbDi/MiJaOpFLhScn3Qp8CBUlrO5Qhli/LF0FarghGZk5lO6TqmjSTcpEiusIjp8WbxI8ZpTkz6NBl2pAS/IMp5iKnsKAvhit7oFRz69UPtnZCXg/rH51N7kwdiz2WMd4WB6RiRT/GPtGqyDNbkqtumWy0wGlrV3xVYxR7ezyMkm125bzUJfbT8i5D9vMdAjmsXYNQgXUI+FNgwjGBRJq2GXaUlq3v2BR/4fQopRO9WEVlgBlGUrZbiBhbd
    client-secret: AgAArNBOt+ykVsP6xOdUDQ+INeqbJEXpbTyooFj8CBGiewNe3/S4GzUpKxocVM6VSjXa3DElAnNkIhwU98GvhnyYDMpSlQkGl1xuOhAvW1e+byElKHOQaZEwr6jSglUFXTZBNs2YJZYihYTv50GymVAuXMXxAgAazCN6ejiIIX84RkRrKNe02/Iwl8DV7D5qt+7REDkSM6/mP72A7X9UrytQf5SDMySjpwu2a0X0xLuMDHz00nJCoSBDpGS7f/wXiROc1uWXvEKw2mhik9hU06sL9xfzpdfOvvFYU7p5uQu1almXBt5vnIV9tHEXAg/ccsbiV/6+YvMWQdUjhkNcs3NEAecxwJmXeqBfKKA2PeFRIipe79xa/jfJmFq9EkCzOKib5AXNWv+xhAVC2lOFLEvfvOVgkSHp32odwPvFCy2X4PDCZ7nMSPNoz4QaCSP9/robn5Rrp8SXAN15YVMAlDZ0WY/cpYoIXQ4ajJPwM6omoJJc9qhObLE+z5pdN7wUVwcWETZEiKSN7zrnmtSpIzfJNNm38u2YMw6iFv08YAa25DBXCPugnfDPpvGiPfd1penssvSkZEBsSUtMd5mpDwSJjctj03NjUFeVL5FrvyBqL375GI3ntYhXEgZSt+C3RBhL66slVQUTkQpFhNEkaHfQ99R0dGA3ScuUkoRWJ+KkWfe3HYBJzeIAu6aAjMvsF5CLPn2PzuROGFkD+TLZbWl+c33Mo8Ef0CS8Mb0Tm0E3t1Q2pxwXhd7akgBfDsN3aWfzISGiz+LdKujTMA4eHhh5jb2bVlLKFUPoAxu+mtYc7RqfGnwLxFOi4c/aYEnKpmkr8Ly7TmaK7tuqj/lsu+6bMJ/pGQgKh9OolfYiFFTlGA==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/name: argocd-oidc-secret
      name: argocd-oidc-secret
      namespace: argocd
