---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://grafana:80
    adminPassword:
      name: grafana-admin-credentials
      key: admin-password
    adminUser:
      name: grafana-admin-credentials
      key: admin-user
