---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: it-tools
spec:
  hostnames:
    - it-tools.g2net.xyz
  parentRefs:
    - name: cilium-shared-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: it-tools
          port: 80
