---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: wallabag-db-dump
spec:
  backupCommand: sh -c 'sqlite3 /data/db/wallabag.sqlite ".timeout 30000" "PRAGMA wal_checkpoint(TRUNCATE);" 2>/dev/null; cp /data/db/wallabag.sqlite /tmp/backup.sqlite && sqlite3 /tmp/backup.sqlite ".dump"'
  pod:
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: wallabag-sqlite-dump
          image: alpine/sqlite:3.53.2
          command:
            - 'sleep'
            - 'infinity'
          volumeMounts:
            - name: wallabag-data
              mountPath: "/data"
      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-data
