---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data
  annotations:
    k8up.io/backup: true
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-data
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: wallabag-data
    namespace: wallabag
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/wallabag/data
    server: 192.168.0.222
    mountOptions:
      - noatime
      - vers=3
      - soft
      - timeo=600
      - retrans=5
      - rsize=8192
      - wsize=8192
      - lookupcache=none
      - tcp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  annotations:
    k8up.io/backup: true
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-images
  annotations:
    k8up.io/backup: true
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: wallabag-images
    namespace: wallabag
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/wallabag/images
    server: 192.168.0.222
    mountOptions:
      - noatime
      - vers=3
      - soft
      - timeo=600
      - retrans=5
      - rsize=8192
      - wsize=8192
      - lookupcache=none
      - tcp
