---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - configmap.yaml
  - service.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - metrics-exporter.yaml
