---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  annotations:
    k8up.io/backup: true
  labels:
    name: qbittorrent-config
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    name: qbittorrent-config
    namespace: media
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/fast/qbittorrent
    server: 192.168.0.222
    mountOptions:
      - noatime
      - vers=3
      - soft
      - timeo=600
      - retrans=5
      - rsize=8192
      - wsize=8192
      - lookupcache=none
      - tcp
