---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: apps/cilium
    repoURL: https://github.com/gedulis12/homelab
    targetRevision: HEAD
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /spec/listeners/0/allowedRoutes
        - /spec/listeners/1/allowedRoutes
        - /spec/listeners/1/tls/certificateRefs/0/group
        - /spec/listeners/1/tls/certificateRefs/0/kind
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/parentRefs/0/group
        - /spec/parentRefs/0/kind
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
        - /spec/rules/0/matches
    - group: cilium.io
      kind: CiliumGatewayClassConfig
      jq:
        - '.spec.telemetry.accessLogs[0] |= with_entries(select(.key != "text"))'
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
