#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: metallb
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  destination:
#    namespace: metallb
#    server: https://kubernetes.default.svc
#  source:
#    path: apps/metallb
#    repoURL: https://github.com/gedulis12/homelab
#    targetRevision: HEAD
#  syncPolicy:
#    automated:
#      allowEmpty: true
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
