---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
  labels:
    app: actualbudget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
    spec:
      containers:
        - name: actualbudget
          image: actualbudget/actual-server:26.7.0
          ports:
            - containerPort: 5006
          env:
            - name: ACTUAL_USER_CREATION_MODE
              value: login
            - name: TZ
              value: Europe/Vilnius
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actualbudget-data
