---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: tvinksonas
      initContainers:
        - name: copy-config
          image: busybox:latest
          command: ['sh', '-xe', '-c']
          args:
            - cp -L -v /config-init/* /config/;
              ls -lahR /config/;
          securityContext:
            runAsUser: 911
            runAsGroup: 911
            runAsNonRoot: true
          volumeMounts:
            - name: config-cm
              mountPath: "/config-init"
            - name: config-pvc
              mountPath: "/config"
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: TZ
              value: "Europe/Vilnius"
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: media-pvc
              mountPath: "/media"
            - name: config-pvc
              mountPath: "/config"
      volumes:
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media
        - name: config-pvc
          persistentVolumeClaim:
            claimName: radarr-config
        - name: config-cm
          configMap:
            name: radarr-cm
