---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    version: 1.23.3
    releaseName: tempo
    valuesFile: values.yaml

resources:
  - pvc.yaml
