apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-cm
data:
  config.xml: |
    <Config>
    <BindAddress>*</BindAddress>
    <Port>9696</Port>
    <SslPort>6969</SslPort>
    <EnableSsl>False</EnableSsl>
    <LaunchBrowser>True</LaunchBrowser>
    <ApiKey>5d4ed5b22db145df8e0aca9288669da3</ApiKey>
    <AuthenticationMethod>Forms</AuthenticationMethod>
    <AuthenticationRequired>Enabled</AuthenticationRequired>
    <Branch>master</Branch>
    <LogLevel>debug</LogLevel>
    <SslCertPath></SslCertPath>
    <SslCertPassword></SslCertPassword>
    <UrlBase></UrlBase>
    <InstanceName>Prowlarr</InstanceName>
    <UpdateMechanism>Docker</UpdateMechanism>
    </Config>
