---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: tvinksonas
      initContainers:
        - name: copy-config
          image: busybox:latest
          command: ['sh', '-xe', '-c']
          args:
            - cp -L -v /config-init/* /config/;
              ls -lahR /config/;
          securityContext:
            runAsUser: 911
            runAsGroup: 911
            runAsNonRoot: true
          volumeMounts:
            - name: config-cm
              mountPath: "/config-init"
            - name: config-pvc
              mountPath: "/config"
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          env:
            - name: TZ
              value: "Europe/Vilnius"
          ports:
            - containerPort: 9696
              protocol: TCP
          volumeMounts:
            - name: config-pvc
              mountPath: "/config"
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: config-cm
          configMap:
            name: prowlarr-cm
