---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: prowlarr-db-dump
spec:
  backupCommand: sh -c 'sqlite3 /config/prowlarr.db .dump'
  pod:
    spec:
      containers:
        - name: prowlarr-sqlite-dump
          image: alpine/sqlite:3.51.2
          command:
            - 'sleep'
            - 'infinity'
          volumeMounts:
            - name: config-pvc
              mountPath: "/config"
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: prowlarr-config
