apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: freshrss-backup
  namespace: freshrss
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-secret
      key: restic-password
    b2:
      bucket: g2net-homelab-backup
      path: freshrss
      accountIDSecretRef:
        name: backup-secret
        key: b2-account-id
      accountKeySecretRef:
        name: backup-secret
        key: b2-account-key
