---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: freshrss-db-dump
spec:
  backupCommand: sh -c 'sqlite3 /data/www/freshrss/data/users/gedas/db.sqlite .dump'
  pod:
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: freshrss-sqlite-dump
          image: alpine/sqlite:3.51.2
          command:
            - 'sleep'
            - 'infinity'
          volumeMounts:
            - name: data-pvc
              mountPath: "/data"
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: freshrss-data
