---
apiVersion: v1
kind: ConfigMap
metadata:
  name: excoredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        log
        ready
        k8s_gateway g2net.xyz {
          resources Ingress Service HTTPRoute GRPCRoute TLSRoute DNSEndpoint
        }
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
