---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: k8s-gateway
    repo: https://k8s-gateway.github.io/k8s_gateway/
    namespace: kube-system
    version: 3.2.7
    releaseName: excoredns
    valuesFile: values.yaml
