---
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    coredns.io/hostname: dns
    tailscale.com/expose: "true"
spec:
  loadBalancerIP: 192.168.0.53
